[project]
name = "sartnameai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Umut Arslan", email = "umtarsln00@icloud.com" }
]
requires-python = ">=3.10"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "pdfplumber>=0.11.10",
    "rich>=15.0.0",
]

[project.scripts]
sartnameai = "sartnameai:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
